Team.create!(name: "India", eliminated: false)
Team.create!(name: "Englsnd", eliminated: false)
Team.create!(name: "Australia", eliminated: false)
Team.create!(name: "South Africa", eliminated: false)
Team.create!(name: "Sri Lanka", eliminated: false)
Team.create!(name: "NewZealand", eliminated: false)
Team.create!(name: "WestIndies", eliminated: false)
Team.create!(name: "Zimbabwe", eliminated: false)
Team.create!(name: "Bangladesh", eliminated: false)
